name: Deploy API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SVR # Nome do environment do reposit칩rio

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      - name: Configurar acesso SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }} # Assim que acessa a secret { secrets.M_NHA_VAR }

      - name: Deploy na VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@145.223.26.174 << 'EOF'
            cd /var/www/sites/api.chat-tasker.com.br || exit 1

            # Atualiza reposit칩rio
            git checkout main
            git pull

            # Para o container atual
            docker compose down

            # Assim que acessa a var { vars.MINHA_VAR }
            # Executa Docker Compose passando vari치veis do GitHub
            PORT_SERVER=${{ secrets.PORT_SERVER }} \
            HOST_DB=${{ secrets.HOST_DB }} \
            PORT_DB=${{ secrets.PORT_DB }} \
            USER_DB=${{ secrets.USER_DB }} \
            PASSWORD_DB=${{ secrets.PASSWORD_DB }} \
            DATABASE_DB=${{ secrets.DATABASE_DB }} \
            REDIS_HOST=${{ secrets.REDIS_HOST }} \
            REDIS_PORT=${{ secrets.REDIS_PORT }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \

            docker-compose -f docker-compose.main.yml up --build -d
          EOF
